### ISSUE TITLE
hi,how can I generate the file FP_data.p if I use the RPlan dataset?

### ISSUE THREAD

**Issue by gogo03** [akshaygadipatil/LayoutGMN-pytorch#2]
I want to follow you codes in the Triplet_data.
thank you very much.

**Comment by agp-ka32** [comment]
Hi @gogo03 ,

In order to generate `FP_data.pkl` file, you will need to first find positive and negative pairs based on IoU metric.
To get a IoU score, you need to first download the [RPLAN dataset](http://staff.ustc.edu.cn/~fuxm/projects/DeepLayout/index.html), and visualize the rooms in the floorplan (for your understanding). 

Then, you can represent each floorplan image as a multi-channel image, where each channel represents a room type. Once you have this, for any given floorplan, you can find its IoU score with any other floorplan in the dataset. Set a threshold of 0.6 for labeling a database floorplan as positive for a query floorplan, and others as negative.

In this way, you can build APN dataset. From there, follow the steps [here](https://github.com/akshaygadipatil/LayoutGMN-pytorch/tree/main/Triplet_data) to get your` FP_data.pkl` file

**Comment by gogo03** [comment]
thanks for your reply.
I have finished generated the .npy files based on your codes and gcn-cnn, but when I run the the file of compute_pairwise_iou.py for one segment,it will cost about ten hours, but for RPLAN dataset,  it has about 75 segments in trains.txt, It means that it will cost about 750 hours to finish this task, which is unacceptable. Can you provide the FP_data.pkl of rfplan dataset. thank you very much.

**Comment by agp-ka32** [comment]
Added the link to download data here: https://github.com/akshaygadipatil/LayoutGMN-pytorch#preparing-layout-graphs.
Closing this issue.
